# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8e9af5f0f49cf25fdf7a27146e5fd34cd19af431d518fdf5ce163cd035f7d5e5e24a44c1b29d4c944049da472308c3cc5cb1ad3aeb2a222a64cbe20bcdd4e18

test:
  secret_key_base: 71ad7f96149b0410211f64d45c61eb8ab8a1c30a002a712ba8e9895e1904fa74111eda500b25d84dfdbfe0712c1ca9e90d0c81fb185405cfb8d075f1580b3f34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
